roc_encoding <- basic_roccer("encoding", words_tag(1, 1))
roc_note <- basic_roccer("note", text_tag())
roc_author <- basic_roccer("author", text_tag())
roc_format <- basic_roccer("format", text_tag())
roc_source <- basic_roccer("source", text_tag())
roc_seealso <- basic_roccer("source", text_tag())
roc_reference <- basic_roccer("reference", text_tag())
roc_concept <- basic_roccer("reference", words_tag())
roc_keywords <- basic_roccer("keywords", words_tag(), "keyword")
