#' Add comments to the Rd file.
#'
#' @usage @@comment This is a comment that will not be user visible.
add_tag_roccer("comment", text_tag())

#' Automatically add the path as an Rd comment.
#' 
#' @usage None: this is added automatically.
add_roccer("path", 
  roc_parser(one = function(roc, path, ...) {
    list(path = roc$path %||% path)
  }),
  rd_out(function(value) {
    paths <- paste(value, collapse = ", ")
    comment <- paste("Generated by roxygen from [", paths, "]", sep = "")
    new_command("comment", comment)
  })
)