#' Namespace: import function from package.
#' 
#' Produces multiple \code{importFrom(package, function)} directives to import
#' selected functions from a package. This is mainly useful for resolving
#' conflicts generated by \code{\link{tag_auto_import}}.
#' 
#' You can do \code{@@importFrom base function} - this is not normally allowed
#' in the \file{NAMESPACE}, but roxygen3 will simply ignore it, but still
#' use it when resolving conflicts.
#' 
#' @usage @@importFrom package function1 function2
#' @auto_import
add_roccer("importFrom", 
  roc_parser(
    function(tag, name) {
      pieces <- str_split(tag, "[[:space:]]+")[[1]]
      if (length(pieces) < 2) {
        stop("@importFrom needs at least two components.", call. = FALSE)
      }
      setNames(rep(pieces[1], length(pieces[-1])), pieces[-1])
    }
  ),
  namespace_out(function(tag) {
    tag <- tag[tag != "base"]
    if (length(tag) == 0) return()
    
    str_c("importFrom(", tag, ",", quote_if_needed(names(tag)), ")", 
      collapse = "\n")
  })
)

#' Namespace: automatically generate import statements.
#'
#' Automatically generates the necessary \code{importFrom} statements
#' to import all external functions used by this function.  See
#' \code{\link{auto_imports}} for more implementation details.
#'
#' If there is a conflict, use \code{tag_importFrom} to resolve it.
#' 
#' You must have the packages declared in \code{DESCRIPTION} Imports.
#'
#' @usage @@auto_import
#' @auto_import
add_roccer("auto_import", 
  roc_parser(one = 
    function(roc, obj, ...) {
      if (is.null(roc$auto_import)) return()
      if (!is.function(obj$value)) return()
      
      auto <- auto_imports(obj$value, obj$name, roc$importFrom)
      list(importFrom = c(auto, roc$importFrom), auto_import = NULL)
    }
  )
)

base_prereqs[["auto_import"]] <- "importFrom"
