roc_comment <- basic_roccer("comment", sentence_tag())

roc_path <- roccer("path", 
  roc_parser(one = function(roc, path, ...) {
    list(path = roc$path %||% path)
  }),
  rd_out(function(value) {
    paths <- paste(value, collapse = ", ")
    comment <- paste("Generated by roxygen from [", paths, "]", sep = "")
    new_command("comment", comment)
  })
)