#' Automatically add the path as an Rd comment.
#' 
#' @usage None: this is added automatically.
setClass("TagPath", contains = "Tag",
  list(path = "character"))

setMethod("defaultTag", c("TagPath", "Object"), function(tag, object) {
  if (isNull(object)) return()
  new("TagPath", path = location(object@srcref))
})

setMethod("writeRd", "TagPath", function(object) {
  paths <- str_c(object@path, collapse = ", ")
  comment <- paste("Generated by roxygen from [", paths, "]", sep = "")
  new_command("comment", comment)
})
