#' Automatically add the path as an Rd comment.
#' 
#' @usage None: this is added automatically.
setClass("TagPath", contains = "Tag",
  list(path = "character"))

setMethod("procBlock", "TagPath", function(tag, block) {
  path <- tag@text %||% getSrcFilename(block@srcref)
  block@tags$path <- TagPath$new(path = path)
  block
})

setMethod("writeRd", "TagPath", function(tag) {
  paths <- paste(tag@text, collapse = ", ")
  comment <- paste("Generated by roxygen from [", paths, "]", sep = "")
  new_command("comment", comment)
})
